In [1]:
import pandas as pd
import numpy as np

In [2]:
portfolio = pd.read_csv('portfolio.csv', index_col=0).dropna(how='any',axis=0)
portfolio

,reward,channels,difficulty,duration,offer_type,id
0,10,"['email', 'mobile', 'social']",10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,10,"['web', 'email', 'mobile', 'social']",10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,0,"['web', 'email', 'mobile']",0,4,informational,3f207df678b143eea3cee63160fa8bed
3,5,"['web', 'email', 'mobile']",5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,5,"['web', 'email']",20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7
5,3,"['web', 'email', 'mobile', 'social']",7,7,discount,2298d6c36e964ae4a3e7e9706d1fb8c2
6,2,"['web', 'email', 'mobile', 'social']",10,10,discount,fafdcd668e3743c1bb461111dcafc2a4
7,0,"['email', 'mobile', 'social']",0,3,informational,5a8bc65990b245e5a138643cd4eb9837
8,5,"['web', 'email', 'mobile', 'social']",5,5,bogo,f19421c1d4aa40978ebb69ca19b0e20d
9,2,"['web', 'email', 'mobile']",10,7,discount,2906b810c7d4411798c6938adc9daaa5

In [3]:
profile = pd.read_csv('profile.csv', index_col=0).dropna(how='any',axis=0).reset_index(drop=True)
profile

,gender,age,id,became_member_on,income
0,F,55,0610b486422d4921ae7d2bf64640c50b,20170715,112000.0
1,F,75,78afa995795e4d85b5d9ceeca43f5fef,20170509,100000.0
2,M,68,e2127556f4f64592b11af22de27a7932,20180426,70000.0
3,M,65,389bc3fa690240e798340f5a15918d5c,20180209,53000.0
4,M,58,2eeac8d8feae4a8cad5a6af0499a211d,20171111,51000.0
...,...,...,...,...,...
14820,F,45,6d5f3a774f3d4714ab0c092238f3a1d7,20180604,54000.0
14821,M,61,2cb4f97358b841b9a9773a7aa05a9d77,20180713,72000.0
14822,M,49,01d26f638c274aa0b965d24cefe3183f,20170126,73000.0
14823,F,83,9dc1421481194dcd9400aec7c9ae6366,20160307,50000.0
14824,F,62,e4052622e5ba45a8b96b59aba68cf068,20170722,82000.0

In [4]:
transcript = pd.read_csv('transcript.csv', index_col=0).dropna(how='any',axis=0).reset_index(drop=True)
transcript

,person,event,value,time
0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0
...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,transaction,{'amount': 1.5899999999999999},714
306530,68213b08d99a4ae1b0dcb72aebd9aa35,transaction,{'amount': 9.53},714
306531,a00058cf10334a308c68e7631c529907,transaction,{'amount': 3.61},714
306532,76ddbd6576844afe811f1a3c0fbb5bec,transaction,{'amount': 3.5300000000000002},714
306533,c02b10e8752c4d8e9b73f918558531f7,transaction,{'amount': 4.05},714

In [5]:
transcript.groupby(['event']).mean()

                       time
event
offer completed  401.052801
offer received   332.579519
offer viewed     354.290515
transaction      381.584334

In [6]:
offer_received = transcript.query('event=="offer received"')
offer_received

,person,event,value,time
0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0
...,...,...,...,...
257882,d087c473b4d247ccb0abfef59ba12b0e,offer received,{'offer id': 'ae264e3637204a6fb9bb56bc8210ddfd'},576
257883,cb23b66c56f64b109d673d5e56574529,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},576
257884,6d5f3a774f3d4714ab0c092238f3a1d7,offer received,{'offer id': '2298d6c36e964ae4a3e7e9706d1fb8c2'},576
257885,9dc1421481194dcd9400aec7c9ae6366,offer received,{'offer id': 'ae264e3637204a6fb9bb56bc8210ddfd'},576
257886,e4052622e5ba45a8b96b59aba68cf068,offer received,{'offer id': '3f207df678b143eea3cee63160fa8bed'},576

In [7]:
offer_viewed = transcript.query('event=="offer viewed"')
offer_viewed

,person,event,value,time
12650,389bc3fa690240e798340f5a15918d5c,offer viewed,{'offer id': 'f19421c1d4aa40978ebb69ca19b0e20d'},0
12651,d1ede868e29245ea91818a903fec04c6,offer viewed,{'offer id': '5a8bc65990b245e5a138643cd4eb9837'},0
12652,102e9454054946fda62242d2e176fdce,offer viewed,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0
12653,02c083884c7d45b39cc68e1314fec56c,offer viewed,{'offer id': 'ae264e3637204a6fb9bb56bc8210ddfd'},0
12655,be8a5d1981a2458d90b255ddc7e0d174,offer viewed,{'offer id': '5a8bc65990b245e5a138643cd4eb9837'},0
...,...,...,...,...
306441,d56386cf344c4829bbf420d1895dca37,offer viewed,{'offer id': '5a8bc65990b245e5a138643cd4eb9837'},714
306450,9b51e8797290403b90d09d864dec4b94,offer viewed,{'offer id': '3f207df678b143eea3cee63160fa8bed'},714
306483,84fb57a7fe8045a8bf6236738ee73a0f,offer viewed,{'offer id': '5a8bc65990b245e5a138643cd4eb9837'},714
306490,abc4359eb34e4e2ca2349da2ddf771b6,offer viewed,{'offer id': '3f207df678b143eea3cee63160fa8bed'},714
306507,8dda575c2a1d44b9ac8e8b07b93d1f8e,offer viewed,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},714

In [8]:
transaction = transcript.query('event=="transaction"')
transaction

,person,event,value,time
12654,02c083884c7d45b39cc68e1314fec56c,transaction,{'amount': 0.8300000000000001},0
12657,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 34.56},0
12659,54890f68699049c2a04d415abc25e717,transaction,{'amount': 13.23},0
12670,b2f1cd155b864803ad8334cdf13c4bd2,transaction,{'amount': 19.51},0
12671,fe97aa22dd3e48c8b143116a8403dd52,transaction,{'amount': 18.97},0
...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,transaction,{'amount': 1.5899999999999999},714
306530,68213b08d99a4ae1b0dcb72aebd9aa35,transaction,{'amount': 9.53},714
306531,a00058cf10334a308c68e7631c529907,transaction,{'amount': 3.61},714
306532,76ddbd6576844afe811f1a3c0fbb5bec,transaction,{'amount': 3.5300000000000002},714
306533,c02b10e8752c4d8e9b73f918558531f7,transaction,{'amount': 4.05},714

In [9]:
offer_completed = transcript.query('event=="offer completed"')
offer_completed

,person,event,value,time
12658,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer completed,{'offer_id': '2906b810c7d4411798c6938adc9daaa5...,0
12672,fe97aa22dd3e48c8b143116a8403dd52,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,0
12679,629fc02d56414d91bca360decdfa9288,offer completed,{'offer_id': '9b98b8c7a33c4b65b9aebfe6a799e6d9...,0
12692,676506bad68e4161b9bbaffeb039626b,offer completed,{'offer_id': 'ae264e3637204a6fb9bb56bc8210ddfd...,0
12697,8f7dd3b2afe14c078eb4f6e6fe4ba97d,offer completed,{'offer_id': '4d5c57ea9a6940dd891ad53e9dbe8da0...,0
...,...,...,...,...
306475,0c027f5f34dd4b9eba0a25785c611273,offer completed,{'offer_id': '2298d6c36e964ae4a3e7e9706d1fb8c2...,714
306497,a6f84f4e976f44508c358cc9aba6d2b3,offer completed,{'offer_id': '2298d6c36e964ae4a3e7e9706d1fb8c2...,714
306506,b895c57e8cd047a8872ce02aa54759d6,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714
306509,8431c16f8e1d440880db371a68f82dd0,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714
306527,24f56b5e1849462093931b164eb803b5,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714

In [10]:
this_person = transcript.query('person=="9fa9ae8f57894cc9a3b8a9bbe0fc1b2f"')
this_person

,person,event,value,time
36,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
12656,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer viewed,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
12657,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 34.56},0
12658,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer completed,{'offer_id': '2906b810c7d4411798c6938adc9daaa5...,0
27850,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 21.55},42
44327,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 32.87},114
51350,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 19.99},156
65854,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 20.97},168
81403,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 31.09},204
110866,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer received,{'offer id': '2298d6c36e964ae4a3e7e9706d1fb8c2'},336
127138,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer viewed,{'offer id': '2298d6c36e964ae4a3e7e9706d1fb8c2'},342
132814,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 18.42},354
132815,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer completed,{'offer_id': '2298d6c36e964ae4a3e7e9706d1fb8c2...,354
145382,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 29.71},390
147220,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 32.53},396
148933,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 33.36},402
150635,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},408
189209,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer viewed,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},462
193194,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 21.13},474
193195,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer completed,{'offer_id': '0b1e1539f2cc45b7b9fa7c272da2e1d7...,474
201606,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},504
221911,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer viewed,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},516
232880,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,transaction,{'amount': 24.3},540
232881,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer completed,{'offer_id': '4d5c57ea9a6940dd891ad53e9dbe8da0...,540

In [11]:
pd.set_option("max_colwidth", 400)
offer_completed_split = offer_completed['value'].str.split("'",expand=True)
offer_completed['value'] = offer_completed_split[3]
offer_completed

C:\Users\kelly\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,person,event,value,time
12658,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,offer completed,2906b810c7d4411798c6938adc9daaa5,0
12672,fe97aa22dd3e48c8b143116a8403dd52,offer completed,fafdcd668e3743c1bb461111dcafc2a4,0
12679,629fc02d56414d91bca360decdfa9288,offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,0
12692,676506bad68e4161b9bbaffeb039626b,offer completed,ae264e3637204a6fb9bb56bc8210ddfd,0
12697,8f7dd3b2afe14c078eb4f6e6fe4ba97d,offer completed,4d5c57ea9a6940dd891ad53e9dbe8da0,0
...,...,...,...,...
306475,0c027f5f34dd4b9eba0a25785c611273,offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,714
306497,a6f84f4e976f44508c358cc9aba6d2b3,offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,714
306506,b895c57e8cd047a8872ce02aa54759d6,offer completed,fafdcd668e3743c1bb461111dcafc2a4,714
306509,8431c16f8e1d440880db371a68f82dd0,offer completed,fafdcd668e3743c1bb461111dcafc2a4,714
306527,24f56b5e1849462093931b164eb803b5,offer completed,fafdcd668e3743c1bb461111dcafc2a4,714

In [12]:
offer_completed_counts = offer_completed.groupby(['person','value'], as_index=False).count()
offer_completed_counts = offer_completed_counts[["person", "value", "event"]].rename(columns={"event":"per_offer_type"})
offer_completed_counts

#TIMES EACH PERSON COMPLETED EACH OFFER TYPE

,person,value,per_offer_type
0,0009655768c64bdeb2e877511632db8f,2906b810c7d4411798c6938adc9daaa5,1
1,0009655768c64bdeb2e877511632db8f,f19421c1d4aa40978ebb69ca19b0e20d,1
2,0009655768c64bdeb2e877511632db8f,fafdcd668e3743c1bb461111dcafc2a4,1
3,0011e0d4e6b944f998e987f904e8c1e5,0b1e1539f2cc45b7b9fa7c272da2e1d7,1
4,0011e0d4e6b944f998e987f904e8c1e5,2298d6c36e964ae4a3e7e9706d1fb8c2,1
...,...,...,...
28991,fffad4f4828548d1b5583907f2e9906b,f19421c1d4aa40978ebb69ca19b0e20d,2
28992,ffff82501cea40309d5fdd7edcca4a07,0b1e1539f2cc45b7b9fa7c272da2e1d7,1
28993,ffff82501cea40309d5fdd7edcca4a07,2906b810c7d4411798c6938adc9daaa5,3
28994,ffff82501cea40309d5fdd7edcca4a07,9b98b8c7a33c4b65b9aebfe6a799e6d9,1
28995,ffff82501cea40309d5fdd7edcca4a07,fafdcd668e3743c1bb461111dcafc2a4,1

In [13]:
offer_completed_counts = offer_completed.groupby(['person'], as_index=False).count()
offer_completed_counts = offer_completed_counts[["person", "event"]].rename(columns={"event":"per_person"})
offer_completed_counts.sort_values('per_person')

#TIMES EACH PERSON COMPLETED A TRANSACTION

                                 person  per_person
5981   787c1f76fcbb417394f951c87dc4c3d9           1
5660   71b61cc2a3004060b66070ff75168a17           1
8843   afc17613b3594acf896bddf6a2226cea           1
10837  d92ab842fbae483cbf5b04fdeec2e9e6           1
10835  d924317fd90048b98f9f891a9db6a335           1
...                                 ...         ...
2972   3b84fac9ca1148bb96b133ced98f565a           6
3132   3ead7d94371041fcab4db5fb57ced95c           6
3133   3eaf1550d25f450e93faeb5a4ab744c1           6
2678   36329ff7770243fbbec5a8f2c3600494           6
12773  ffff82501cea40309d5fdd7edcca4a07           6

[12774 rows x 2 columns]

In [14]:
transaction_split = transaction['value'].str.split(": ",expand=True)
transaction_split = transaction_split[1].str.split("}",expand=True)
transaction['value'] = transaction_split[0].astype(float)
transaction = transaction.rename(columns={'value':'paid'})
transaction

C:\Users\kelly\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

                                  person        event   paid  time
12654   02c083884c7d45b39cc68e1314fec56c  transaction   0.83     0
12657   9fa9ae8f57894cc9a3b8a9bbe0fc1b2f  transaction  34.56     0
12659   54890f68699049c2a04d415abc25e717  transaction  13.23     0
12670   b2f1cd155b864803ad8334cdf13c4bd2  transaction  19.51     0
12671   fe97aa22dd3e48c8b143116a8403dd52  transaction  18.97     0
...                                  ...          ...    ...   ...
306529  b3a1272bc9904337b331bf348c3e8c17  transaction   1.59   714
306530  68213b08d99a4ae1b0dcb72aebd9aa35  transaction   9.53   714
306531  a00058cf10334a308c68e7631c529907  transaction   3.61   714
306532  76ddbd6576844afe811f1a3c0fbb5bec  transaction   3.53   714
306533  c02b10e8752c4d8e9b73f918558531f7  transaction   4.05   714

[138953 rows x 4 columns]

In [15]:
total_spent = transaction.groupby(['person'], as_index=False)['paid'].sum()
total_spent
total_spent.sort_values('paid')
#TOTAL AMOUNT SPENT IN TIMEFRAME PER PERSON

                                 person     paid
1139   11d87e606c2f4d649fe09a5e84d048c2     0.05
4694   4828b93dd6dd44eb9ec8417f0564a9b9     0.05
16343  fc3444ae44044a218e160522f7de8d8d     0.05
10000  999338157fd54f639b089cef0038e06a     0.05
3580   37ca07481c124d98ac1eaca5ee1f4146     0.10
...                                 ...      ...
7492   73afdeca19e349b98f09e928644610f8  1319.97
6366   626df8678e2a4953b9098246418c9cfa  1321.42
11422  ae6f43089b674728a50b8727252d3305  1327.74
15693  f1d65ae63f174b8f80fa063adcaa63b7  1365.66
3929   3c8d541112a74af99e88abbd0692f00e  1608.69

[16578 rows x 2 columns]

In [16]:
offer_completed.replace(to_replace ="ae264e3637204a6fb9bb56bc8210ddfd",
                 value ="zero",inplace = True)
offer_completed.replace(to_replace ="4d5c57ea9a6940dd891ad53e9dbe8da0",
                 value ="one",inplace = True)
offer_completed.replace(to_replace ="3f207df678b143eea3cee63160fa8bed",
                 value ="two",inplace = True)
offer_completed.replace(to_replace ="9b98b8c7a33c4b65b9aebfe6a799e6d9",
                 value ="three",inplace = True)
offer_completed.replace(to_replace ="0b1e1539f2cc45b7b9fa7c272da2e1d7",
                 value ="four",inplace = True)
offer_completed.replace(to_replace ="2298d6c36e964ae4a3e7e9706d1fb8c2",
                 value ="five",inplace = True)
offer_completed.replace(to_replace ="fafdcd668e3743c1bb461111dcafc2a4",
                 value ="six",inplace = True)
offer_completed.replace(to_replace ="5a8bc65990b245e5a138643cd4eb9837",
                 value ="seven",inplace = True)
offer_completed.replace(to_replace ="f19421c1d4aa40978ebb69ca19b0e20d",
                 value ="eight",inplace = True)
offer_completed.replace(to_replace ="2906b810c7d4411798c6938adc9daaa5",
                 value ="nine",inplace = True)
offer_completed

C:\Users\kelly\Anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:4172: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

                                  person            event  value  time
12658   9fa9ae8f57894cc9a3b8a9bbe0fc1b2f  offer completed   nine     0
12672   fe97aa22dd3e48c8b143116a8403dd52  offer completed    six     0
12679   629fc02d56414d91bca360decdfa9288  offer completed  three     0
12692   676506bad68e4161b9bbaffeb039626b  offer completed   zero     0
12697   8f7dd3b2afe14c078eb4f6e6fe4ba97d  offer completed    one     0
...                                  ...              ...    ...   ...
306475  0c027f5f34dd4b9eba0a25785c611273  offer completed   five   714
306497  a6f84f4e976f44508c358cc9aba6d2b3  offer completed   five   714
306506  b895c57e8cd047a8872ce02aa54759d6  offer completed    six   714
306509  8431c16f8e1d440880db371a68f82dd0  offer completed    six   714
306527  24f56b5e1849462093931b164eb803b5  offer completed    six   714

[33579 rows x 4 columns]

In [17]:
combined = pd.merge(offer_completed, profile, left_on='person', right_on='id', how='left')
combined.drop(columns =['person', 'event','time','became_member_on'],inplace=True)
combined.dropna(inplace=True)
combined.loc[combined['value']=='two']

Empty DataFrame
Columns: [value, gender, age, id, income]
Index: []

In [18]:
customers = ['zero', 'one', 'three', 'four', 'five', 'six', 'eight', 'nine']
def demographics (x):
    age = round(combined.loc[combined['value'] == x]['age'].dropna().mean())
    income = round(combined.loc[combined['value'] == x]['income'].dropna().mean())
    gender = combined.loc[combined['value'] == x]['gender'].dropna().value_counts(normalize=True)
    desc = combined.loc[combined['value'] == x].describe()
    print(f'customer {x}')
    print(f'average age of customer {x}: {age}')
    print(f'average income of customer {x}: {income}')
    print(gender)
    print(desc)
    print('=====')
for x in customers:
    demographics(x)

customer zero
average age of customer zero: 57
average income of customer zero: 72178
F    0.507793
M    0.476073
O    0.016133
Name: gender, dtype: float64
               age         income
count  3657.000000    3657.000000
mean     56.594750   72178.288214
std      16.288575   21143.614868
min      18.000000   30000.000000
25%      46.000000   56000.000000
50%      57.000000   72000.000000
75%      67.000000   88000.000000
max     100.000000  120000.000000
=====
customer one
average age of customer one: 57
average income of customer one: 72566
F    0.527492
M    0.458912
O    0.013595
Name: gender, dtype: float64
               age         income
count  3310.000000    3310.000000
mean     56.944411   72565.558912
std      16.354025   21251.827104
min      18.000000   30000.000000
25%      47.000000   57000.000000
50%      57.000000   72000.000000
75%      68.000000   88000.000000
max     100.000000  120000.000000
=====
customer three
average age of customer three: 55
average income of customer three: 68268
M    0.505014
F    0.477316
O    0.017670
Name: gender, dtype: float64
               age         income
count  4188.000000    4188.000000
mean     55.339064   68267.908309
std      16.740453   21677.596199
min      18.000000   30000.000000
25%      44.000000   52000.000000
50%      56.000000   68000.000000
75%      67.000000   84000.000000
max     101.000000  120000.000000
=====
customer four
average age of customer four: 57
average income of customer four: 71876
F    0.502953
M    0.478441
O    0.018606
Name: gender, dtype: float64
               age         income
count  3386.000000    3386.000000
mean     56.667750   71876.255168
std      16.283468   21478.367743
min      18.000000   30000.000000
25%      47.000000   55000.000000
50%      57.000000   72000.000000
75%      68.000000   88000.000000
max     101.000000  120000.000000
=====
customer five
average age of customer five: 55
average income of customer five: 66925
M    0.534793
F    0.451494
O    0.013713
Name: gender, dtype: float64
               age         income
count  4886.000000    4886.000000
mean     54.846500   66925.092100
std      17.339484   21524.081792
min      18.000000   30000.000000
25%      43.000000   51000.000000
50%      56.000000   66000.000000
75%      67.000000   82000.000000
max     101.000000  120000.000000
=====
customer six
average age of customer six: 55
average income of customer six: 67601
M    0.543874
F    0.442934
O    0.013192
Name: gender, dtype: float64
               age         income
count  5003.000000    5003.000000
mean     55.235259   67600.639616
std      17.005985   21818.899831
min      18.000000   30000.000000
25%      44.000000   51000.000000
50%      56.000000   66000.000000
75%      67.000000   82000.000000
max     101.000000  120000.000000
=====
customer eight
average age of customer eight: 56
average income of customer eight: 68583
M    0.520838
F    0.462832
O    0.016330
Name: gender, dtype: float64
               age         income
count  4103.000000    4103.000000
mean     55.682427   68582.744333
std      17.195078   21777.584873
min      18.000000   30000.000000
25%      45.000000   52000.000000
50%      56.000000   67000.000000
75%      67.000000   84000.000000
max     101.000000  120000.000000
=====
customer nine
average age of customer nine: 56
average income of customer nine: 69698
M    0.511378
F    0.473280
O    0.015341
Name: gender, dtype: float64
               age         income
count  3911.000000    3911.000000
mean     56.088468   69698.031194
std      16.745648   21204.052928
min      18.000000   30000.000000
25%      45.000000   54000.000000
50%      57.000000   69000.000000
75%      67.000000   85000.000000
max     101.000000  120000.000000
=====

In [19]:
profile_fixed = profile.rename(columns={'id':'person'})
combined=transcript.merge(profile_fixed, on='person', how='left')
combined_clean = combined['value'].str.split("'",expand=True)
combined['value'] = combined_clean[3]
portfolio_fixed = portfolio.rename(columns={'id':'value'})
combined_3=combined.merge(portfolio_fixed, on='value', how="left").sort_values(['person', 'time', 'value',])
combined_3 = pd.merge(combined_3,transaction,how="left",suffixes=(False,'_r'))
combined_3 = combined_3.rename(columns={'value':'offer_id'})
combined_3 = combined_3.replace(['offer received'],'1 offer received')
combined_3 = combined_3.replace(['offer viewed'],'2 offer viewed')
combined_3 = combined_3.replace(['transaction'],'4 transaction')
combined_3 = combined_3.replace(['offer completed'],'3 offer completed')
# combined_3 = combined_3.sort_values(['person', 'time'])

combined_3

,person,event,offer_id,time,gender,age,became_member_on,income,reward,channels,difficulty,duration,offer_type,paid
0,0009655768c64bdeb2e877511632db8f,1 offer received,5a8bc65990b245e5a138643cd4eb9837,168,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,NaN
1,0009655768c64bdeb2e877511632db8f,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,192,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,NaN
2,0009655768c64bdeb2e877511632db8f,4 transaction,None,228,M,33.0,20170421.0,72000.0,NaN,NaN,NaN,NaN,NaN,22.16
3,0009655768c64bdeb2e877511632db8f,1 offer received,3f207df678b143eea3cee63160fa8bed,336,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,NaN
4,0009655768c64bdeb2e877511632db8f,2 offer viewed,3f207df678b143eea3cee63160fa8bed,372,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306529,ffff82501cea40309d5fdd7edcca4a07,3 offer completed,2906b810c7d4411798c6938adc9daaa5,576,F,45.0,20161125.0,62000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,NaN
306530,ffff82501cea40309d5fdd7edcca4a07,4 transaction,None,576,F,45.0,20161125.0,62000.0,NaN,NaN,NaN,NaN,NaN,14.23
306531,ffff82501cea40309d5fdd7edcca4a07,2 offer viewed,2906b810c7d4411798c6938adc9daaa5,582,F,45.0,20161125.0,62000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,NaN
306532,ffff82501cea40309d5fdd7edcca4a07,4 transaction,None,606,F,45.0,20161125.0,62000.0,NaN,NaN,NaN,NaN,NaN,10.12
306533,ffff82501cea40309d5fdd7edcca4a07,4 transaction,None,648,F,45.0,20161125.0,62000.0,NaN,NaN,NaN,NaN,NaN,18.91

In [20]:
# if "event" column of row says "offer completed" and "time" column of row == "time" column of row + 1, insert "paid" column
#     value of row +1 into "paid" column of row and delete row +1

i=0

for index, row in combined_3.iterrows():
    if row['event'] == "3 offer completed":
        next_index = index+1
        next_row = combined_3.loc[[next_index]].values.tolist()
        prev_index = index-1
        prev_row = combined_3.loc[[prev_index]].values.tolist()
        next_checker = next_row[-1][1]
        prev_checker = prev_row[-1][1]
        if next_checker == "4 transaction":
            price = next_row[-1][-1]
            combined_3.at[i,'paid'] = price
            i = i+1
        elif prev_checker == "4 transaction":
            price = prev_row[-1][-1]
            combined_3.at[i,'paid'] = price
            i=i+1
        else:
            combined_3.at[i,'paid'] = 0
            i=i+1
    else:
        combined_3.at[i,'paid'] = 0
        i = i+1
combined_3 = combined_3[(combined_3["event"]!="4 transaction")]
combined_4 = combined_3.reset_index(drop=True)
combined_4.head(60)

,person,event,offer_id,time,gender,age,became_member_on,income,reward,channels,difficulty,duration,offer_type,paid
0,0009655768c64bdeb2e877511632db8f,1 offer received,5a8bc65990b245e5a138643cd4eb9837,168,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00
1,0009655768c64bdeb2e877511632db8f,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,192,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00
2,0009655768c64bdeb2e877511632db8f,1 offer received,3f207df678b143eea3cee63160fa8bed,336,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00
3,0009655768c64bdeb2e877511632db8f,2 offer viewed,3f207df678b143eea3cee63160fa8bed,372,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00
4,0009655768c64bdeb2e877511632db8f,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00
5,0009655768c64bdeb2e877511632db8f,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,414,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,8.57
6,0009655768c64bdeb2e877511632db8f,2 offer viewed,f19421c1d4aa40978ebb69ca19b0e20d,456,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00
7,0009655768c64bdeb2e877511632db8f,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,504,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00
8,0009655768c64bdeb2e877511632db8f,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,528,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,14.11
9,0009655768c64bdeb2e877511632db8f,2 offer viewed,fafdcd668e3743c1bb461111dcafc2a4,540,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00
10,0009655768c64bdeb2e877511632db8f,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00
11,0009655768c64bdeb2e877511632db8f,3 offer completed,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,10.27
12,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,168,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00
13,00116118485d4dfda04fdbaba9a87b5c,2 offer viewed,f19421c1d4aa40978ebb69ca19b0e20d,216,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00
14,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,576,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00
15,00116118485d4dfda04fdbaba9a87b5c,2 offer viewed,f19421c1d4aa40978ebb69ca19b0e20d,630,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00
16,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,3f207df678b143eea3cee63160fa8bed,0,O,40.0,20180109.0,57000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00
17,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,3f207df678b143eea3cee63160fa8bed,6,O,40.0,20180109.0,57000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00
18,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00
19,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,2298d6c36e964ae4a3e7e9706d1fb8c2,186,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00
20,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,252,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.93
21,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,5a8bc65990b245e5a138643cd4eb9837,336,O,40.0,20180109.0,57000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00
22,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,354,O,40.0,20180109.0,57000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00
23,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,408,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00
24,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,0b1e1539f2cc45b7b9fa7c272da2e1d7,432,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00
25,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00
26,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,9b98b8c7a33c4b65b9aebfe6a799e6d9,516,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00
27,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,0b1e1539f2cc45b7b9fa7c272da2e1d7,576,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00
28,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,576,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,22.05
29,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,0,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00
30,0020c2b971eb4e9188eac86d93036a77,2 offer viewed,fafdcd668e3743c1bb461111dcafc2a4,12,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00
31,0020c2b971eb4e9188eac86d93036a77,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,54,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.63
32,0020c2b971eb4e9188eac86d93036a77,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,168,F,59.0,20160304.0,90000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,0.00
33,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,336,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00
34,0020c2b971eb4e9188eac86d93036a77,1 offer received,4d5c57ea9a6940dd891ad53e9dbe8da0,408,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00
35,0020c2b971eb4e9188eac86d93036a77,2 offer viewed,4d5c57ea9a6940dd891ad53e9dbe8da0,426,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00
36,0020c2b971eb4e9188eac86d93036a77,1 offer received,5a8bc65990b245e5a138643cd4eb9837,504,F,59.0,20160304.0,90000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00
37,0020c2b971eb4e9188eac86d93036a77,3 offer completed,4d5c57ea9a6940dd891ad53e9dbe8da0,510,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00
38,0020c2b971eb4e9188eac86d93036a77,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,510,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.24
39,0020c2b971eb4e9188eac86d93036a77,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,660,F,59.0,20160304.0,90000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00
40,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00
41,0020ccbbb6d84e358d3414a3ff76cffd,2 offer viewed,2298d6c36e964ae4a3e7e9706d1fb8c2,168,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00
42,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,222,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.65
43,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,336,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00
44,0020ccbbb6d84e358d3414a3ff76cffd,2 offer viewed,f19421c1d4aa40978ebb69ca19b0e20d,348,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00
45,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,378,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,14.53
46,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,5a8bc65990b245e5a138643cd4eb9837,408,F,24.0,20161111.0,60000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00
47,0020ccbbb6d84e358d3414a3ff76cffd,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,408,F,24.0,20161111.0,60000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00
48,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00
49,0020ccbbb6d84e358d3414a3ff76cffd,2 offer viewed,9b98b8c7a33c4b65b9aebfe6a799e6d9,582,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00
50,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,600,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,10.32
51,003d66b6608740288d6cc97a6903f4f0,1 offer received,5a8bc65990b245e5a138643cd4eb9837,0,F,26.0,20170621.0,73000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00
52,003d66b6608740288d6cc97a6903f4f0,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,36,F,26.0,20170621.0,73000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00
53,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00
54,003d66b6608740288d6cc97a6903f4f0,2 offer viewed,fafdcd668e3743c1bb461111dcafc2a4,300,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00
55,003d66b6608740288d6cc97a6903f4f0,1 offer received,3f207df678b143eea3cee63160fa8bed,336,F,26.0,20170621.0,73000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00
56,003d66b6608740288d6cc97a6903f4f0,2 offer viewed,3f207df678b143eea3cee63160fa8bed,372,F,26.0,20170621.0,73000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00
57,003d66b6608740288d6cc97a6903f4f0,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,384,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,3.66
58,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,408,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00
59,003d66b6608740288d6cc97a6903f4f0,2 offer viewed,fafdcd668e3743c1bb461111dcafc2a4,420,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00

In [21]:
combined_4["offer_received"] =""
combined_4["offer_viewed"] =""

i=0
for index, row in combined_3.iterrows():
    if row['event'] == "1 offer received":
        view_time = row['time']
        combined_4.at[i,'offer_received'] = view_time
        i = i+1
    elif row['event'] == "2 offer viewed":
        view_time = row['time']
        combined_4.at[i,'offer_viewed'] = view_time
        i = i+1
    else:
        i = i+1
combined_4.head(60)

,person,event,offer_id,time,gender,age,became_member_on,income,reward,channels,difficulty,duration,offer_type,paid,offer_received,offer_viewed
0,0009655768c64bdeb2e877511632db8f,1 offer received,5a8bc65990b245e5a138643cd4eb9837,168,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,168,
1,0009655768c64bdeb2e877511632db8f,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,192,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,,192
2,0009655768c64bdeb2e877511632db8f,1 offer received,3f207df678b143eea3cee63160fa8bed,336,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,
3,0009655768c64bdeb2e877511632db8f,2 offer viewed,3f207df678b143eea3cee63160fa8bed,372,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,,372
4,0009655768c64bdeb2e877511632db8f,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,408,
5,0009655768c64bdeb2e877511632db8f,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,414,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,8.57,,
6,0009655768c64bdeb2e877511632db8f,2 offer viewed,f19421c1d4aa40978ebb69ca19b0e20d,456,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,,456
7,0009655768c64bdeb2e877511632db8f,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,504,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,504,
8,0009655768c64bdeb2e877511632db8f,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,528,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,14.11,,
9,0009655768c64bdeb2e877511632db8f,2 offer viewed,fafdcd668e3743c1bb461111dcafc2a4,540,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,,540
10,0009655768c64bdeb2e877511632db8f,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,576,
11,0009655768c64bdeb2e877511632db8f,3 offer completed,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,10.27,,
12,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,168,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,168,
13,00116118485d4dfda04fdbaba9a87b5c,2 offer viewed,f19421c1d4aa40978ebb69ca19b0e20d,216,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,,216
14,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,576,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,576,
15,00116118485d4dfda04fdbaba9a87b5c,2 offer viewed,f19421c1d4aa40978ebb69ca19b0e20d,630,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,,630
16,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,3f207df678b143eea3cee63160fa8bed,0,O,40.0,20180109.0,57000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,0,
17,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,3f207df678b143eea3cee63160fa8bed,6,O,40.0,20180109.0,57000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,,6
18,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,168,
19,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,2298d6c36e964ae4a3e7e9706d1fb8c2,186,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,,186
20,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,252,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.93,,
21,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,5a8bc65990b245e5a138643cd4eb9837,336,O,40.0,20180109.0,57000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,336,
22,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,354,O,40.0,20180109.0,57000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,,354
23,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,408,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,408,
24,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,0b1e1539f2cc45b7b9fa7c272da2e1d7,432,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,,432
25,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,504,
26,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,9b98b8c7a33c4b65b9aebfe6a799e6d9,516,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,,516
27,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,0b1e1539f2cc45b7b9fa7c272da2e1d7,576,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,,
28,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,576,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,22.05,,
29,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,0,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,0,
30,0020c2b971eb4e9188eac86d93036a77,2 offer viewed,fafdcd668e3743c1bb461111dcafc2a4,12,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,,12
31,0020c2b971eb4e9188eac86d93036a77,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,54,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.63,,
32,0020c2b971eb4e9188eac86d93036a77,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,168,F,59.0,20160304.0,90000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,0.00,168,
33,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,336,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,336,
34,0020c2b971eb4e9188eac86d93036a77,1 offer received,4d5c57ea9a6940dd891ad53e9dbe8da0,408,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,408,
35,0020c2b971eb4e9188eac86d93036a77,2 offer viewed,4d5c57ea9a6940dd891ad53e9dbe8da0,426,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,,426
36,0020c2b971eb4e9188eac86d93036a77,1 offer received,5a8bc65990b245e5a138643cd4eb9837,504,F,59.0,20160304.0,90000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,504,
37,0020c2b971eb4e9188eac86d93036a77,3 offer completed,4d5c57ea9a6940dd891ad53e9dbe8da0,510,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,,
38,0020c2b971eb4e9188eac86d93036a77,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,510,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.24,,
39,0020c2b971eb4e9188eac86d93036a77,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,660,F,59.0,20160304.0,90000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,,660
40,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,168,
41,0020ccbbb6d84e358d3414a3ff76cffd,2 offer viewed,2298d6c36e964ae4a3e7e9706d1fb8c2,168,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,,168
42,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,222,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.65,,
43,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,336,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,336,
44,0020ccbbb6d84e358d3414a3ff76cffd,2 offer viewed,f19421c1d4aa40978ebb69ca19b0e20d,348,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,,348
45,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,378,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,14.53,,
46,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,5a8bc65990b245e5a138643cd4eb9837,408,F,24.0,20161111.0,60000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,408,
47,0020ccbbb6d84e358d3414a3ff76cffd,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,408,F,24.0,20161111.0,60000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,,408
48,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,504,
49,0020ccbbb6d84e358d3414a3ff76cffd,2 offer viewed,9b98b8c7a33c4b65b9aebfe6a799e6d9,582,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,,582
50,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,600,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,10.32,,
51,003d66b6608740288d6cc97a6903f4f0,1 offer received,5a8bc65990b245e5a138643cd4eb9837,0,F,26.0,20170621.0,73000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,0,
52,003d66b6608740288d6cc97a6903f4f0,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,36,F,26.0,20170621.0,73000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,,36
53,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,168,
54,003d66b6608740288d6cc97a6903f4f0,2 offer viewed,fafdcd668e3743c1bb461111dcafc2a4,300,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,,300
55,003d66b6608740288d6cc97a6903f4f0,1 offer received,3f207df678b143eea3cee63160fa8bed,336,F,26.0,20170621.0,73000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,
56,003d66b6608740288d6cc97a6903f4f0,2 offer viewed,3f207df678b143eea3cee63160fa8bed,372,F,26.0,20170621.0,73000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,,372
57,003d66b6608740288d6cc97a6903f4f0,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,384,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,3.66,,
58,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,408,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,408,
59,003d66b6608740288d6cc97a6903f4f0,2 offer viewed,fafdcd668e3743c1bb461111dcafc2a4,420,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,,420

In [22]:
combined_5 = combined_4
combined_5['offer_viewed_y_n'] = ""
combined_5

,person,event,offer_id,time,gender,age,became_member_on,income,reward,channels,difficulty,duration,offer_type,paid,offer_received,offer_viewed,offer_viewed_y_n
0,0009655768c64bdeb2e877511632db8f,1 offer received,5a8bc65990b245e5a138643cd4eb9837,168,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,168,,
1,0009655768c64bdeb2e877511632db8f,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,192,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,,192,
2,0009655768c64bdeb2e877511632db8f,1 offer received,3f207df678b143eea3cee63160fa8bed,336,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,,
3,0009655768c64bdeb2e877511632db8f,2 offer viewed,3f207df678b143eea3cee63160fa8bed,372,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,,372,
4,0009655768c64bdeb2e877511632db8f,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,408,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167576,ffff82501cea40309d5fdd7edcca4a07,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,F,45.0,20161125.0,62000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,7.79,,,
167577,ffff82501cea40309d5fdd7edcca4a07,2 offer viewed,9b98b8c7a33c4b65b9aebfe6a799e6d9,534,F,45.0,20161125.0,62000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,,534,
167578,ffff82501cea40309d5fdd7edcca4a07,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,F,45.0,20161125.0,62000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,576,,
167579,ffff82501cea40309d5fdd7edcca4a07,3 offer completed,2906b810c7d4411798c6938adc9daaa5,576,F,45.0,20161125.0,62000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,14.23,,,
167580,ffff82501cea40309d5fdd7edcca4a07,2 offer viewed,2906b810c7d4411798c6938adc9daaa5,582,F,45.0,20161125.0,62000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,,582,

In [23]:
# add "offer viewed" time to "offer received" row and drop "offer viewed" row
i=0
# index=0
last_row = combined_5.index[-1]
for index, row in combined_5.iterrows():
    if row['event'] == "1 offer received":
        if index != last_row:
            next_index = index+1
    #         print(next_index)
            next_row = combined_5.loc[[next_index]].values.tolist()
            next_check_person = next_row[0][0]
            next_check_event = next_row[0][1]
            if index != 0:
                prev_index = index-1
                prev_row = combined_5.loc[[prev_index]].values.tolist()
                prev_check_person = next_row[0][0]
                prev_check_event = next_row[0][1]
            if row['person'] == next_check_person and next_row[0][1] == next_check_event:
                view_time = next_row[0][3]
                combined_5.at[index,'offer_viewed'] = view_time
                combined_5.at[index,'offer_viewed_y_n'] = "Y"
                i=i+1
            elif row['person'] == prev_check_person and prev_row[0][1] == prev_check_event:
                view_time = prev_row[0][3]
                combined_5.at[index,'offer_viewed'] = view_time
                combined_5.at[index,'offer_viewed_y_n'] = "Y"
                i=i+1
            else:
                combined_5.at[index,'offer_viewed'] = "not viewed"
                combined_5.at[index,'offer_viewed_y_n'] = "N"
                combined_5.at[index,'paid'] = 0
                i=i+1

combined_5.head(60)

### YOU STOPPED DEBUGGING HERE

,person,event,offer_id,time,gender,age,became_member_on,income,reward,channels,difficulty,duration,offer_type,paid,offer_received,offer_viewed,offer_viewed_y_n
0,0009655768c64bdeb2e877511632db8f,1 offer received,5a8bc65990b245e5a138643cd4eb9837,168,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,168,192,Y
1,0009655768c64bdeb2e877511632db8f,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,192,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,,192,
2,0009655768c64bdeb2e877511632db8f,1 offer received,3f207df678b143eea3cee63160fa8bed,336,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,372,Y
3,0009655768c64bdeb2e877511632db8f,2 offer viewed,3f207df678b143eea3cee63160fa8bed,372,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,,372,
4,0009655768c64bdeb2e877511632db8f,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,408,414,Y
5,0009655768c64bdeb2e877511632db8f,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,414,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,8.57,,,
6,0009655768c64bdeb2e877511632db8f,2 offer viewed,f19421c1d4aa40978ebb69ca19b0e20d,456,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,,456,
7,0009655768c64bdeb2e877511632db8f,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,504,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,504,528,Y
8,0009655768c64bdeb2e877511632db8f,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,528,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,14.11,,,
9,0009655768c64bdeb2e877511632db8f,2 offer viewed,fafdcd668e3743c1bb461111dcafc2a4,540,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,,540,
10,0009655768c64bdeb2e877511632db8f,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,576,576,Y
11,0009655768c64bdeb2e877511632db8f,3 offer completed,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,10.27,,,
12,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,168,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,168,216,Y
13,00116118485d4dfda04fdbaba9a87b5c,2 offer viewed,f19421c1d4aa40978ebb69ca19b0e20d,216,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,,216,
14,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,576,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,576,630,Y
15,00116118485d4dfda04fdbaba9a87b5c,2 offer viewed,f19421c1d4aa40978ebb69ca19b0e20d,630,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,,630,
16,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,3f207df678b143eea3cee63160fa8bed,0,O,40.0,20180109.0,57000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,0,6,Y
17,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,3f207df678b143eea3cee63160fa8bed,6,O,40.0,20180109.0,57000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,,6,
18,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,168,186,Y
19,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,2298d6c36e964ae4a3e7e9706d1fb8c2,186,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,,186,
20,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,252,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.93,,,
21,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,5a8bc65990b245e5a138643cd4eb9837,336,O,40.0,20180109.0,57000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,336,354,Y
22,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,354,O,40.0,20180109.0,57000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,,354,
23,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,408,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,408,432,Y
24,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,0b1e1539f2cc45b7b9fa7c272da2e1d7,432,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,,432,
25,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,504,516,Y
26,0011e0d4e6b944f998e987f904e8c1e5,2 offer viewed,9b98b8c7a33c4b65b9aebfe6a799e6d9,516,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,,516,
27,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,0b1e1539f2cc45b7b9fa7c272da2e1d7,576,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,,,
28,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,576,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,22.05,,,
29,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,0,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,0,12,Y
30,0020c2b971eb4e9188eac86d93036a77,2 offer viewed,fafdcd668e3743c1bb461111dcafc2a4,12,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,,12,
31,0020c2b971eb4e9188eac86d93036a77,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,54,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.63,,,
32,0020c2b971eb4e9188eac86d93036a77,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,168,F,59.0,20160304.0,90000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,0.00,168,336,Y
33,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,336,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,336,408,Y
34,0020c2b971eb4e9188eac86d93036a77,1 offer received,4d5c57ea9a6940dd891ad53e9dbe8da0,408,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,408,426,Y
35,0020c2b971eb4e9188eac86d93036a77,2 offer viewed,4d5c57ea9a6940dd891ad53e9dbe8da0,426,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,,426,
36,0020c2b971eb4e9188eac86d93036a77,1 offer received,5a8bc65990b245e5a138643cd4eb9837,504,F,59.0,20160304.0,90000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,504,510,Y
37,0020c2b971eb4e9188eac86d93036a77,3 offer completed,4d5c57ea9a6940dd891ad53e9dbe8da0,510,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,,,
38,0020c2b971eb4e9188eac86d93036a77,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,510,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.24,,,
39,0020c2b971eb4e9188eac86d93036a77,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,660,F,59.0,20160304.0,90000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,,660,
40,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,168,168,Y
41,0020ccbbb6d84e358d3414a3ff76cffd,2 offer viewed,2298d6c36e964ae4a3e7e9706d1fb8c2,168,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,,168,
42,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,222,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.65,,,
43,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,336,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,336,348,Y
44,0020ccbbb6d84e358d3414a3ff76cffd,2 offer viewed,f19421c1d4aa40978ebb69ca19b0e20d,348,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,,348,
45,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,378,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,14.53,,,
46,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,5a8bc65990b245e5a138643cd4eb9837,408,F,24.0,20161111.0,60000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,408,408,Y
47,0020ccbbb6d84e358d3414a3ff76cffd,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,408,F,24.0,20161111.0,60000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,,408,
48,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,504,582,Y
49,0020ccbbb6d84e358d3414a3ff76cffd,2 offer viewed,9b98b8c7a33c4b65b9aebfe6a799e6d9,582,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,,582,
50,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,600,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,10.32,,,
51,003d66b6608740288d6cc97a6903f4f0,1 offer received,5a8bc65990b245e5a138643cd4eb9837,0,F,26.0,20170621.0,73000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,0,36,Y
52,003d66b6608740288d6cc97a6903f4f0,2 offer viewed,5a8bc65990b245e5a138643cd4eb9837,36,F,26.0,20170621.0,73000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,,36,
53,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,168,300,Y
54,003d66b6608740288d6cc97a6903f4f0,2 offer viewed,fafdcd668e3743c1bb461111dcafc2a4,300,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,,300,
55,003d66b6608740288d6cc97a6903f4f0,1 offer received,3f207df678b143eea3cee63160fa8bed,336,F,26.0,20170621.0,73000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,372,Y
56,003d66b6608740288d6cc97a6903f4f0,2 offer viewed,3f207df678b143eea3cee63160fa8bed,372,F,26.0,20170621.0,73000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,,372,
57,003d66b6608740288d6cc97a6903f4f0,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,384,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,3.66,,,
58,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,408,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,408,420,Y
59,003d66b6608740288d6cc97a6903f4f0,2 offer viewed,fafdcd668e3743c1bb461111dcafc2a4,420,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,,420,

In [24]:
# i=0            
# for index, row in combined_5.iterrows():
#     if row['offer_viewed'] == "not viewed":
#         combined_5.at[i,'offer_viewed_y_n'] = "N"
#         i=i+1

# i=0            
# for index, row in combined_5.iterrows():
#     if row['offer_viewed_y_n'] == "N":
#         combined_5.at[i,'offer_viewed'] = "not viewed"
#         i=i+1
        
combined_5 = combined_5[(combined_5["event"]!="2 offer viewed")]
combined_6 = combined_5.reset_index(drop=True)
combined_6.head(60)

,person,event,offer_id,time,gender,age,became_member_on,income,reward,channels,difficulty,duration,offer_type,paid,offer_received,offer_viewed,offer_viewed_y_n
0,0009655768c64bdeb2e877511632db8f,1 offer received,5a8bc65990b245e5a138643cd4eb9837,168,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,168,192,Y
1,0009655768c64bdeb2e877511632db8f,1 offer received,3f207df678b143eea3cee63160fa8bed,336,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,372,Y
2,0009655768c64bdeb2e877511632db8f,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,408,414,Y
3,0009655768c64bdeb2e877511632db8f,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,414,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,8.57,,,
4,0009655768c64bdeb2e877511632db8f,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,504,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,504,528,Y
5,0009655768c64bdeb2e877511632db8f,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,528,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,14.11,,,
6,0009655768c64bdeb2e877511632db8f,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,576,576,Y
7,0009655768c64bdeb2e877511632db8f,3 offer completed,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,10.27,,,
8,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,168,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,168,216,Y
9,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,576,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,576,630,Y
10,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,3f207df678b143eea3cee63160fa8bed,0,O,40.0,20180109.0,57000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,0,6,Y
11,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,168,186,Y
12,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,252,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.93,,,
13,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,5a8bc65990b245e5a138643cd4eb9837,336,O,40.0,20180109.0,57000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,336,354,Y
14,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,408,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,408,432,Y
15,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,504,516,Y
16,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,0b1e1539f2cc45b7b9fa7c272da2e1d7,576,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,,,
17,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,576,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,22.05,,,
18,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,0,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,0,12,Y
19,0020c2b971eb4e9188eac86d93036a77,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,54,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.63,,,
20,0020c2b971eb4e9188eac86d93036a77,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,168,F,59.0,20160304.0,90000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,0.00,168,336,Y
21,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,336,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,336,408,Y
22,0020c2b971eb4e9188eac86d93036a77,1 offer received,4d5c57ea9a6940dd891ad53e9dbe8da0,408,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,408,426,Y
23,0020c2b971eb4e9188eac86d93036a77,1 offer received,5a8bc65990b245e5a138643cd4eb9837,504,F,59.0,20160304.0,90000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,504,510,Y
24,0020c2b971eb4e9188eac86d93036a77,3 offer completed,4d5c57ea9a6940dd891ad53e9dbe8da0,510,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,,,
25,0020c2b971eb4e9188eac86d93036a77,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,510,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.24,,,
26,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,168,168,Y
27,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,222,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.65,,,
28,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,336,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,336,348,Y
29,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,378,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,14.53,,,
30,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,5a8bc65990b245e5a138643cd4eb9837,408,F,24.0,20161111.0,60000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,408,408,Y
31,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,504,582,Y
32,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,600,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,10.32,,,
33,003d66b6608740288d6cc97a6903f4f0,1 offer received,5a8bc65990b245e5a138643cd4eb9837,0,F,26.0,20170621.0,73000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,0,36,Y
34,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,168,300,Y
35,003d66b6608740288d6cc97a6903f4f0,1 offer received,3f207df678b143eea3cee63160fa8bed,336,F,26.0,20170621.0,73000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,372,Y
36,003d66b6608740288d6cc97a6903f4f0,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,384,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,3.66,,,
37,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,408,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,408,420,Y
38,003d66b6608740288d6cc97a6903f4f0,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,504,F,26.0,20170621.0,73000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,504,504,Y
39,003d66b6608740288d6cc97a6903f4f0,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,504,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,5.01,,,
40,003d66b6608740288d6cc97a6903f4f0,3 offer completed,0b1e1539f2cc45b7b9fa7c272da2e1d7,696,F,26.0,20170621.0,73000.0,5.0,"['web', 'email']",20.0,10.0,discount,2.25,,,
41,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,5a8bc65990b245e5a138643cd4eb9837,0,F,19.0,20160809.0,65000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,0,36,Y
42,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,168,186,Y
43,00426fe3ffde4c6b9cb9ad6d077a13ea,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,258,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,16.97,,,
44,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,336,F,19.0,20160809.0,65000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,336,408,Y
45,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,2906b810c7d4411798c6938adc9daaa5,408,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,408,576,Y
46,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,576,not viewed,N
47,004b041fbfe44859945daa2c7f79ee64,1 offer received,3f207df678b143eea3cee63160fa8bed,168,F,55.0,20180508.0,74000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,168,504,Y
48,004b041fbfe44859945daa2c7f79ee64,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,504,F,55.0,20180508.0,74000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,504,510,Y
49,004b041fbfe44859945daa2c7f79ee64,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,534,F,55.0,20180508.0,74000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,27.92,,,
50,004b041fbfe44859945daa2c7f79ee64,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,576,F,55.0,20180508.0,74000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,576,576,Y
51,004b041fbfe44859945daa2c7f79ee64,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,714,F,55.0,20180508.0,74000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,19.93,,,
52,004c5799adbf42868b9cff0396190900,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,M,54.0,20160331.0,99000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,168,174,Y
53,004c5799adbf42868b9cff0396190900,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,222,M,54.0,20160331.0,99000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,43.21,,,
54,004c5799adbf42868b9cff0396190900,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,336,M,54.0,20160331.0,99000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,0.00,336,336,Y
55,004c5799adbf42868b9cff0396190900,3 offer completed,ae264e3637204a6fb9bb56bc8210ddfd,336,M,54.0,20160331.0,99000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,25.61,,,
56,004c5799adbf42868b9cff0396190900,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,408,408,Y
57,004c5799adbf42868b9cff0396190900,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,432,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,22.82,,,
58,004c5799adbf42868b9cff0396190900,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,504,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,504,516,Y
59,004c5799adbf42868b9cff0396190900,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,558,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,35.91,,,

In [25]:
combined_6["offer_completed"] = ""
combined_6["offer_completed_y_n"] = ""
combined_7 = combined_6
combined_7.head(60)

,person,event,offer_id,time,gender,age,became_member_on,income,reward,channels,difficulty,duration,offer_type,paid,offer_received,offer_viewed,offer_viewed_y_n,offer_completed,offer_completed_y_n
0,0009655768c64bdeb2e877511632db8f,1 offer received,5a8bc65990b245e5a138643cd4eb9837,168,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,168,192,Y,,
1,0009655768c64bdeb2e877511632db8f,1 offer received,3f207df678b143eea3cee63160fa8bed,336,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,372,Y,,
2,0009655768c64bdeb2e877511632db8f,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,408,414,Y,,
3,0009655768c64bdeb2e877511632db8f,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,414,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,8.57,,,,,
4,0009655768c64bdeb2e877511632db8f,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,504,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,504,528,Y,,
5,0009655768c64bdeb2e877511632db8f,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,528,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,14.11,,,,,
6,0009655768c64bdeb2e877511632db8f,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,576,576,Y,,
7,0009655768c64bdeb2e877511632db8f,3 offer completed,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,10.27,,,,,
8,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,168,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,168,216,Y,,
9,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,576,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,576,630,Y,,
10,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,3f207df678b143eea3cee63160fa8bed,0,O,40.0,20180109.0,57000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,0,6,Y,,
11,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,168,186,Y,,
12,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,252,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.93,,,,,
13,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,5a8bc65990b245e5a138643cd4eb9837,336,O,40.0,20180109.0,57000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,336,354,Y,,
14,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,408,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,408,432,Y,,
15,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,504,516,Y,,
16,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,0b1e1539f2cc45b7b9fa7c272da2e1d7,576,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,,,,,
17,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,576,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,22.05,,,,,
18,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,0,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,0,12,Y,,
19,0020c2b971eb4e9188eac86d93036a77,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,54,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.63,,,,,
20,0020c2b971eb4e9188eac86d93036a77,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,168,F,59.0,20160304.0,90000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,0.00,168,336,Y,,
21,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,336,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,336,408,Y,,
22,0020c2b971eb4e9188eac86d93036a77,1 offer received,4d5c57ea9a6940dd891ad53e9dbe8da0,408,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,408,426,Y,,
23,0020c2b971eb4e9188eac86d93036a77,1 offer received,5a8bc65990b245e5a138643cd4eb9837,504,F,59.0,20160304.0,90000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,504,510,Y,,
24,0020c2b971eb4e9188eac86d93036a77,3 offer completed,4d5c57ea9a6940dd891ad53e9dbe8da0,510,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,,,,,
25,0020c2b971eb4e9188eac86d93036a77,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,510,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.24,,,,,
26,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,168,168,Y,,
27,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,222,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.65,,,,,
28,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,336,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,336,348,Y,,
29,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,378,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,14.53,,,,,
30,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,5a8bc65990b245e5a138643cd4eb9837,408,F,24.0,20161111.0,60000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,408,408,Y,,
31,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,504,582,Y,,
32,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,600,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,10.32,,,,,
33,003d66b6608740288d6cc97a6903f4f0,1 offer received,5a8bc65990b245e5a138643cd4eb9837,0,F,26.0,20170621.0,73000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,0,36,Y,,
34,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,168,300,Y,,
35,003d66b6608740288d6cc97a6903f4f0,1 offer received,3f207df678b143eea3cee63160fa8bed,336,F,26.0,20170621.0,73000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,372,Y,,
36,003d66b6608740288d6cc97a6903f4f0,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,384,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,3.66,,,,,
37,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,408,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,408,420,Y,,
38,003d66b6608740288d6cc97a6903f4f0,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,504,F,26.0,20170621.0,73000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,504,504,Y,,
39,003d66b6608740288d6cc97a6903f4f0,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,504,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,5.01,,,,,
40,003d66b6608740288d6cc97a6903f4f0,3 offer completed,0b1e1539f2cc45b7b9fa7c272da2e1d7,696,F,26.0,20170621.0,73000.0,5.0,"['web', 'email']",20.0,10.0,discount,2.25,,,,,
41,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,5a8bc65990b245e5a138643cd4eb9837,0,F,19.0,20160809.0,65000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,0,36,Y,,
42,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,168,186,Y,,
43,00426fe3ffde4c6b9cb9ad6d077a13ea,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,258,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,16.97,,,,,
44,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,336,F,19.0,20160809.0,65000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,336,408,Y,,
45,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,2906b810c7d4411798c6938adc9daaa5,408,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,408,576,Y,,
46,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,576,not viewed,N,,
47,004b041fbfe44859945daa2c7f79ee64,1 offer received,3f207df678b143eea3cee63160fa8bed,168,F,55.0,20180508.0,74000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,168,504,Y,,
48,004b041fbfe44859945daa2c7f79ee64,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,504,F,55.0,20180508.0,74000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,504,510,Y,,
49,004b041fbfe44859945daa2c7f79ee64,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,534,F,55.0,20180508.0,74000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,27.92,,,,,
50,004b041fbfe44859945daa2c7f79ee64,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,576,F,55.0,20180508.0,74000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,576,576,Y,,
51,004b041fbfe44859945daa2c7f79ee64,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,714,F,55.0,20180508.0,74000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,19.93,,,,,
52,004c5799adbf42868b9cff0396190900,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,M,54.0,20160331.0,99000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,168,174,Y,,
53,004c5799adbf42868b9cff0396190900,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,222,M,54.0,20160331.0,99000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,43.21,,,,,
54,004c5799adbf42868b9cff0396190900,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,336,M,54.0,20160331.0,99000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,0.00,336,336,Y,,
55,004c5799adbf42868b9cff0396190900,3 offer completed,ae264e3637204a6fb9bb56bc8210ddfd,336,M,54.0,20160331.0,99000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,25.61,,,,,
56,004c5799adbf42868b9cff0396190900,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,408,408,Y,,
57,004c5799adbf42868b9cff0396190900,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,432,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,22.82,,,,,
58,004c5799adbf42868b9cff0396190900,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,504,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,504,516,Y,,
59,004c5799adbf42868b9cff0396190900,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,558,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,35.91,,,,,

In [26]:
# add "offer completed" y/n column to "offer received" row, copy the "price" from "offer completed" to "offer received",
#     and drop "offer completed" rows
i=0
last_row = combined_7.index[-1]
for index, row in combined_7.iterrows():
    if row['event'] == "1 offer received":
        if index != last_row:
            next_index = index+1
            next_row = combined_7.loc[[next_index]].values.tolist()
            if row['person'] == next_row[0][0] and next_row[0][1] == "3 offer completed":
                complete_time = next_row[0][3]
                combined_7.at[index,'offer_completed'] = complete_time
                price = next_row[0][13]
                combined_7.at[index,'paid'] = price
                combined_7.at[index,'offer_completed_y_n'] = "Y"
                i=i+1
            else:
                combined_7.at[index,'offer_completed'] = "not completed"
                combined_7.at[index,'offer_completed_y_n'] = "N"
                combined_7.at[index,'paid'] = 0
                i=i+1
combined_7.head(60)

,person,event,offer_id,time,gender,age,became_member_on,income,reward,channels,difficulty,duration,offer_type,paid,offer_received,offer_viewed,offer_viewed_y_n,offer_completed,offer_completed_y_n
0,0009655768c64bdeb2e877511632db8f,1 offer received,5a8bc65990b245e5a138643cd4eb9837,168,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,168,192,Y,not completed,N
1,0009655768c64bdeb2e877511632db8f,1 offer received,3f207df678b143eea3cee63160fa8bed,336,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,372,Y,not completed,N
2,0009655768c64bdeb2e877511632db8f,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,8.57,408,414,Y,414,Y
3,0009655768c64bdeb2e877511632db8f,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,414,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,8.57,,,,,
4,0009655768c64bdeb2e877511632db8f,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,504,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,14.11,504,528,Y,528,Y
5,0009655768c64bdeb2e877511632db8f,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,528,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,14.11,,,,,
6,0009655768c64bdeb2e877511632db8f,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,10.27,576,576,Y,576,Y
7,0009655768c64bdeb2e877511632db8f,3 offer completed,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,10.27,,,,,
8,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,168,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,168,216,Y,not completed,N
9,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,576,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,576,630,Y,not completed,N
10,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,3f207df678b143eea3cee63160fa8bed,0,O,40.0,20180109.0,57000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,0,6,Y,not completed,N
11,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.93,168,186,Y,252,Y
12,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,252,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.93,,,,,
13,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,5a8bc65990b245e5a138643cd4eb9837,336,O,40.0,20180109.0,57000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,336,354,Y,not completed,N
14,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,408,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,408,432,Y,not completed,N
15,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,504,516,Y,576,Y
16,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,0b1e1539f2cc45b7b9fa7c272da2e1d7,576,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,,,,,
17,0011e0d4e6b944f998e987f904e8c1e5,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,576,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,22.05,,,,,
18,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,0,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.63,0,12,Y,54,Y
19,0020c2b971eb4e9188eac86d93036a77,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,54,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.63,,,,,
20,0020c2b971eb4e9188eac86d93036a77,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,168,F,59.0,20160304.0,90000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,0.00,168,336,Y,not completed,N
21,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,336,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,336,408,Y,not completed,N
22,0020c2b971eb4e9188eac86d93036a77,1 offer received,4d5c57ea9a6940dd891ad53e9dbe8da0,408,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,408,426,Y,not completed,N
23,0020c2b971eb4e9188eac86d93036a77,1 offer received,5a8bc65990b245e5a138643cd4eb9837,504,F,59.0,20160304.0,90000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,504,510,Y,510,Y
24,0020c2b971eb4e9188eac86d93036a77,3 offer completed,4d5c57ea9a6940dd891ad53e9dbe8da0,510,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,,,,,
25,0020c2b971eb4e9188eac86d93036a77,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,510,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.24,,,,,
26,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.65,168,168,Y,222,Y
27,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,2298d6c36e964ae4a3e7e9706d1fb8c2,222,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.65,,,,,
28,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,336,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,14.53,336,348,Y,378,Y
29,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,378,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,14.53,,,,,
30,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,5a8bc65990b245e5a138643cd4eb9837,408,F,24.0,20161111.0,60000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,408,408,Y,not completed,N
31,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,10.32,504,582,Y,600,Y
32,0020ccbbb6d84e358d3414a3ff76cffd,3 offer completed,9b98b8c7a33c4b65b9aebfe6a799e6d9,600,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,10.32,,,,,
33,003d66b6608740288d6cc97a6903f4f0,1 offer received,5a8bc65990b245e5a138643cd4eb9837,0,F,26.0,20170621.0,73000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,0,36,Y,not completed,N
34,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,168,300,Y,not completed,N
35,003d66b6608740288d6cc97a6903f4f0,1 offer received,3f207df678b143eea3cee63160fa8bed,336,F,26.0,20170621.0,73000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,3.66,336,372,Y,384,Y
36,003d66b6608740288d6cc97a6903f4f0,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,384,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,3.66,,,,,
37,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,408,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,408,420,Y,not completed,N
38,003d66b6608740288d6cc97a6903f4f0,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,504,F,26.0,20170621.0,73000.0,5.0,"['web', 'email']",20.0,10.0,discount,5.01,504,504,Y,504,Y
39,003d66b6608740288d6cc97a6903f4f0,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,504,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,5.01,,,,,
40,003d66b6608740288d6cc97a6903f4f0,3 offer completed,0b1e1539f2cc45b7b9fa7c272da2e1d7,696,F,26.0,20170621.0,73000.0,5.0,"['web', 'email']",20.0,10.0,discount,2.25,,,,,
41,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,5a8bc65990b245e5a138643cd4eb9837,0,F,19.0,20160809.0,65000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,0,36,Y,not completed,N
42,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,16.97,168,186,Y,258,Y
43,00426fe3ffde4c6b9cb9ad6d077a13ea,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,258,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,16.97,,,,,
44,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,336,F,19.0,20160809.0,65000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,336,408,Y,not completed,N
45,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,2906b810c7d4411798c6938adc9daaa5,408,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,408,576,Y,not completed,N
46,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,576,not viewed,N,not completed,N
47,004b041fbfe44859945daa2c7f79ee64,1 offer received,3f207df678b143eea3cee63160fa8bed,168,F,55.0,20180508.0,74000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,168,504,Y,not completed,N
48,004b041fbfe44859945daa2c7f79ee64,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,504,F,55.0,20180508.0,74000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,27.92,504,510,Y,534,Y
49,004b041fbfe44859945daa2c7f79ee64,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,534,F,55.0,20180508.0,74000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,27.92,,,,,
50,004b041fbfe44859945daa2c7f79ee64,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,576,F,55.0,20180508.0,74000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,19.93,576,576,Y,714,Y
51,004b041fbfe44859945daa2c7f79ee64,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,714,F,55.0,20180508.0,74000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,19.93,,,,,
52,004c5799adbf42868b9cff0396190900,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,M,54.0,20160331.0,99000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,43.21,168,174,Y,222,Y
53,004c5799adbf42868b9cff0396190900,3 offer completed,fafdcd668e3743c1bb461111dcafc2a4,222,M,54.0,20160331.0,99000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,43.21,,,,,
54,004c5799adbf42868b9cff0396190900,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,336,M,54.0,20160331.0,99000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,25.61,336,336,Y,336,Y
55,004c5799adbf42868b9cff0396190900,3 offer completed,ae264e3637204a6fb9bb56bc8210ddfd,336,M,54.0,20160331.0,99000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,25.61,,,,,
56,004c5799adbf42868b9cff0396190900,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,22.82,408,408,Y,432,Y
57,004c5799adbf42868b9cff0396190900,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,432,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,22.82,,,,,
58,004c5799adbf42868b9cff0396190900,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,504,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,35.91,504,516,Y,558,Y
59,004c5799adbf42868b9cff0396190900,3 offer completed,f19421c1d4aa40978ebb69ca19b0e20d,558,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,35.91,,,,,

In [27]:
combined_7 = combined_7[(combined_7["event"]!="3 offer completed")]
combined_8 = combined_7.reset_index(drop=True)
combined_8.head(60)

,person,event,offer_id,time,gender,age,became_member_on,income,reward,channels,difficulty,duration,offer_type,paid,offer_received,offer_viewed,offer_viewed_y_n,offer_completed,offer_completed_y_n
0,0009655768c64bdeb2e877511632db8f,1 offer received,5a8bc65990b245e5a138643cd4eb9837,168,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,168,192,Y,not completed,N
1,0009655768c64bdeb2e877511632db8f,1 offer received,3f207df678b143eea3cee63160fa8bed,336,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,372,Y,not completed,N
2,0009655768c64bdeb2e877511632db8f,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,8.57,408,414,Y,414,Y
3,0009655768c64bdeb2e877511632db8f,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,504,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,14.11,504,528,Y,528,Y
4,0009655768c64bdeb2e877511632db8f,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,10.27,576,576,Y,576,Y
5,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,168,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,168,216,Y,not completed,N
6,00116118485d4dfda04fdbaba9a87b5c,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,576,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,0.00,576,630,Y,not completed,N
7,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,3f207df678b143eea3cee63160fa8bed,0,O,40.0,20180109.0,57000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,0,6,Y,not completed,N
8,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,O,40.0,20180109.0,57000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.93,168,186,Y,252,Y
9,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,5a8bc65990b245e5a138643cd4eb9837,336,O,40.0,20180109.0,57000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,336,354,Y,not completed,N
10,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,408,O,40.0,20180109.0,57000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,408,432,Y,not completed,N
11,0011e0d4e6b944f998e987f904e8c1e5,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,O,40.0,20180109.0,57000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,504,516,Y,576,Y
12,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,0,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,17.63,0,12,Y,54,Y
13,0020c2b971eb4e9188eac86d93036a77,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,168,F,59.0,20160304.0,90000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,0.00,168,336,Y,not completed,N
14,0020c2b971eb4e9188eac86d93036a77,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,336,F,59.0,20160304.0,90000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,336,408,Y,not completed,N
15,0020c2b971eb4e9188eac86d93036a77,1 offer received,4d5c57ea9a6940dd891ad53e9dbe8da0,408,F,59.0,20160304.0,90000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,0.00,408,426,Y,not completed,N
16,0020c2b971eb4e9188eac86d93036a77,1 offer received,5a8bc65990b245e5a138643cd4eb9837,504,F,59.0,20160304.0,90000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,504,510,Y,510,Y
17,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,168,F,24.0,20161111.0,60000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,11.65,168,168,Y,222,Y
18,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,336,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,14.53,336,348,Y,378,Y
19,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,5a8bc65990b245e5a138643cd4eb9837,408,F,24.0,20161111.0,60000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,408,408,Y,not completed,N
20,0020ccbbb6d84e358d3414a3ff76cffd,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,F,24.0,20161111.0,60000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,10.32,504,582,Y,600,Y
21,003d66b6608740288d6cc97a6903f4f0,1 offer received,5a8bc65990b245e5a138643cd4eb9837,0,F,26.0,20170621.0,73000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,0,36,Y,not completed,N
22,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,168,300,Y,not completed,N
23,003d66b6608740288d6cc97a6903f4f0,1 offer received,3f207df678b143eea3cee63160fa8bed,336,F,26.0,20170621.0,73000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,3.66,336,372,Y,384,Y
24,003d66b6608740288d6cc97a6903f4f0,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,408,F,26.0,20170621.0,73000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,0.00,408,420,Y,not completed,N
25,003d66b6608740288d6cc97a6903f4f0,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,504,F,26.0,20170621.0,73000.0,5.0,"['web', 'email']",20.0,10.0,discount,5.01,504,504,Y,504,Y
26,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,5a8bc65990b245e5a138643cd4eb9837,0,F,19.0,20160809.0,65000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,0,36,Y,not completed,N
27,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,16.97,168,186,Y,258,Y
28,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,336,F,19.0,20160809.0,65000.0,5.0,"['web', 'email']",20.0,10.0,discount,0.00,336,408,Y,not completed,N
29,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,2906b810c7d4411798c6938adc9daaa5,408,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,408,576,Y,not completed,N
30,00426fe3ffde4c6b9cb9ad6d077a13ea,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,F,19.0,20160809.0,65000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,576,not viewed,N,not completed,N
31,004b041fbfe44859945daa2c7f79ee64,1 offer received,3f207df678b143eea3cee63160fa8bed,168,F,55.0,20180508.0,74000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,168,504,Y,not completed,N
32,004b041fbfe44859945daa2c7f79ee64,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,504,F,55.0,20180508.0,74000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,27.92,504,510,Y,534,Y
33,004b041fbfe44859945daa2c7f79ee64,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,576,F,55.0,20180508.0,74000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,19.93,576,576,Y,714,Y
34,004c5799adbf42868b9cff0396190900,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,168,M,54.0,20160331.0,99000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,43.21,168,174,Y,222,Y
35,004c5799adbf42868b9cff0396190900,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,336,M,54.0,20160331.0,99000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,25.61,336,336,Y,336,Y
36,004c5799adbf42868b9cff0396190900,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,22.82,408,408,Y,432,Y
37,004c5799adbf42868b9cff0396190900,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,504,M,54.0,20160331.0,99000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,35.91,504,516,Y,558,Y
38,004c5799adbf42868b9cff0396190900,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,576,M,54.0,20160331.0,99000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,33.67,576,576,Y,576,Y
39,005500a7188546ff8a767329a2f7c76a,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,0,M,56.0,20171209.0,47000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,0.00,0,60,Y,not completed,N
40,005500a7188546ff8a767329a2f7c76a,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,168,M,56.0,20171209.0,47000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,0.00,168,186,Y,not completed,N
41,005500a7188546ff8a767329a2f7c76a,1 offer received,2906b810c7d4411798c6938adc9daaa5,408,M,56.0,20171209.0,47000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,408,504,Y,not completed,N
42,005500a7188546ff8a767329a2f7c76a,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,M,56.0,20171209.0,47000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,504,576,Y,not completed,N
43,005500a7188546ff8a767329a2f7c76a,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,576,M,56.0,20171209.0,47000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,9.03,576,576,Y,582,Y
44,0056df74b63b4298809f0b375a304cf4,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,0,M,54.0,20160821.0,91000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,27.86,0,24,Y,132,Y
45,0056df74b63b4298809f0b375a304cf4,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,408,M,54.0,20160821.0,91000.0,5.0,"['web', 'email']",20.0,10.0,discount,27.59,408,414,Y,414,Y
46,0056df74b63b4298809f0b375a304cf4,1 offer received,3f207df678b143eea3cee63160fa8bed,504,M,54.0,20160821.0,91000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,504,528,Y,not completed,N
47,0056df74b63b4298809f0b375a304cf4,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,576,M,54.0,20160821.0,91000.0,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,29.77,576,576,Y,576,Y
48,0063def0f9c14bc4805322a488839b32,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,168,NaN,NaN,NaN,NaN,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,0.00,168,186,Y,not completed,N
49,0063def0f9c14bc4805322a488839b32,1 offer received,2298d6c36e964ae4a3e7e9706d1fb8c2,336,NaN,NaN,NaN,NaN,3.0,"['web', 'email', 'mobile', 'social']",7.0,7.0,discount,0.00,336,342,Y,not completed,N
50,0063def0f9c14bc4805322a488839b32,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,408,NaN,NaN,NaN,NaN,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,0.00,408,414,Y,not completed,N
51,0063def0f9c14bc4805322a488839b32,1 offer received,5a8bc65990b245e5a138643cd4eb9837,504,NaN,NaN,NaN,NaN,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,504,510,Y,not completed,N
52,0063def0f9c14bc4805322a488839b32,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,576,NaN,NaN,NaN,NaN,5.0,"['web', 'email']",20.0,10.0,discount,0.00,576,576,Y,not completed,N
53,0069a50874d846438e58acff5e594725,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,336,NaN,NaN,NaN,NaN,5.0,"['web', 'email']",20.0,10.0,discount,0.00,336,408,Y,not completed,N
54,0069a50874d846438e58acff5e594725,1 offer received,3f207df678b143eea3cee63160fa8bed,408,NaN,NaN,NaN,NaN,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,408,504,Y,not completed,N
55,0069a50874d846438e58acff5e594725,1 offer received,2906b810c7d4411798c6938adc9daaa5,504,NaN,NaN,NaN,NaN,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,0.00,504,552,Y,not completed,N
56,0069a50874d846438e58acff5e594725,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,NaN,NaN,NaN,NaN,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,7.97,576,696,Y,696,Y
57,00715b6e55c3431cb56ff7307eb19675,1 offer received,ae264e3637204a6fb9bb56bc8210ddfd,0,F,58.0,20171207.0,119000.0,10.0,"['email', 'mobile', 'social']",10.0,7.0,bogo,27.26,0,12,Y,12,Y
58,00715b6e55c3431cb56ff7307eb19675,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,168,F,58.0,20171207.0,119000.0,5.0,"['web', 'email']",20.0,10.0,discount,28.73,168,210,Y,210,Y
59,00715b6e55c3431cb56ff7307eb19675,1 offer received,4d5c57ea9a6940dd891ad53e9dbe8da0,336,F,58.0,20171207.0,119000.0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,17.86,336,342,Y,342,Y

In [28]:
combined_8 = combined_8.dropna()
combined_8 = combined_8.reset_index(drop=True)
combined_8

,person,event,offer_id,time,gender,age,became_member_on,income,reward,channels,difficulty,duration,offer_type,paid,offer_received,offer_viewed,offer_viewed_y_n,offer_completed,offer_completed_y_n
0,0009655768c64bdeb2e877511632db8f,1 offer received,5a8bc65990b245e5a138643cd4eb9837,168,M,33.0,20170421.0,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,168,192,Y,not completed,N
1,0009655768c64bdeb2e877511632db8f,1 offer received,3f207df678b143eea3cee63160fa8bed,336,M,33.0,20170421.0,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,372,Y,not completed,N
2,0009655768c64bdeb2e877511632db8f,1 offer received,f19421c1d4aa40978ebb69ca19b0e20d,408,M,33.0,20170421.0,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,8.57,408,414,Y,414,Y
3,0009655768c64bdeb2e877511632db8f,1 offer received,fafdcd668e3743c1bb461111dcafc2a4,504,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,14.11,504,528,Y,528,Y
4,0009655768c64bdeb2e877511632db8f,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,M,33.0,20170421.0,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,10.27,576,576,Y,576,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66496,ffff82501cea40309d5fdd7edcca4a07,1 offer received,0b1e1539f2cc45b7b9fa7c272da2e1d7,168,F,45.0,20161125.0,62000.0,5.0,"['web', 'email']",20.0,10.0,discount,22.88,168,174,Y,198,Y
66497,ffff82501cea40309d5fdd7edcca4a07,1 offer received,2906b810c7d4411798c6938adc9daaa5,336,F,45.0,20161125.0,62000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,15.57,336,354,Y,384,Y
66498,ffff82501cea40309d5fdd7edcca4a07,1 offer received,2906b810c7d4411798c6938adc9daaa5,408,F,45.0,20161125.0,62000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,17.55,408,414,Y,414,Y
66499,ffff82501cea40309d5fdd7edcca4a07,1 offer received,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,F,45.0,20161125.0,62000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,7.79,504,504,Y,504,Y
66500,ffff82501cea40309d5fdd7edcca4a07,1 offer received,2906b810c7d4411798c6938adc9daaa5,576,F,45.0,20161125.0,62000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,14.23,576,576,Y,576,Y

In [33]:
combined_8=combined_8.drop(['time', 'event'], axis = 1)
combined_8['became_member_on'] = pd.to_datetime(combined_8['became_member_on'], format='%Y%m%d')
combined_8

,person,offer_id,gender,age,became_member_on,income,reward,channels,difficulty,duration,offer_type,paid,offer_received,offer_viewed,offer_viewed_y_n,offer_completed,offer_completed_y_n
0,0009655768c64bdeb2e877511632db8f,5a8bc65990b245e5a138643cd4eb9837,M,33.0,2017-04-21,72000.0,0.0,"['email', 'mobile', 'social']",0.0,3.0,informational,0.00,168,192,Y,not completed,N
1,0009655768c64bdeb2e877511632db8f,3f207df678b143eea3cee63160fa8bed,M,33.0,2017-04-21,72000.0,0.0,"['web', 'email', 'mobile']",0.0,4.0,informational,0.00,336,372,Y,not completed,N
2,0009655768c64bdeb2e877511632db8f,f19421c1d4aa40978ebb69ca19b0e20d,M,33.0,2017-04-21,72000.0,5.0,"['web', 'email', 'mobile', 'social']",5.0,5.0,bogo,8.57,408,414,Y,414,Y
3,0009655768c64bdeb2e877511632db8f,fafdcd668e3743c1bb461111dcafc2a4,M,33.0,2017-04-21,72000.0,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,14.11,504,528,Y,528,Y
4,0009655768c64bdeb2e877511632db8f,2906b810c7d4411798c6938adc9daaa5,M,33.0,2017-04-21,72000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,10.27,576,576,Y,576,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66496,ffff82501cea40309d5fdd7edcca4a07,0b1e1539f2cc45b7b9fa7c272da2e1d7,F,45.0,2016-11-25,62000.0,5.0,"['web', 'email']",20.0,10.0,discount,22.88,168,174,Y,198,Y
66497,ffff82501cea40309d5fdd7edcca4a07,2906b810c7d4411798c6938adc9daaa5,F,45.0,2016-11-25,62000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,15.57,336,354,Y,384,Y
66498,ffff82501cea40309d5fdd7edcca4a07,2906b810c7d4411798c6938adc9daaa5,F,45.0,2016-11-25,62000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,17.55,408,414,Y,414,Y
66499,ffff82501cea40309d5fdd7edcca4a07,9b98b8c7a33c4b65b9aebfe6a799e6d9,F,45.0,2016-11-25,62000.0,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,7.79,504,504,Y,504,Y
66500,ffff82501cea40309d5fdd7edcca4a07,2906b810c7d4411798c6938adc9daaa5,F,45.0,2016-11-25,62000.0,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,14.23,576,576,Y,576,Y

In [34]:
combined_8.to_csv('transactions.csv',index=False)

In [30]:
# factors = difficulty, reward, duration, type, channels
# demographics = gender, age, income

# to make tableau processing easier, add y/n columns

#determine which "channels" are most likely to lead to the offer being viewed

#determine which demographics are most likely to view the offer

#of offers that are viewed, determine do statistical analysis to determine which factors  
#     are most likely to return a completed order

#of offers that are viewed, determine do statistical analysis to determine which demographics 
#     are most likely to return a completed order

# determine appx how much various demographics are willing ot spend per offer

# determine most and least successful offers

# use ML to predict which demographics will complete an order